[package]
name = "ehr_icpindia_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.12.0"
candid = "0.10.0"

serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"